### PR TITLE
Refactor limit calculations to allow consistency across all data types

### PR DESCRIPTION
**Pull request by andrjohns**
Hi Chris,

The current structure of the package is focused around SR-type data, which makes equivalent use with PR and RC data a bit difficult.

For example, while a user can request both adjusted and unadjusted limits for SR data:
```r
funnel_plot(numerators, denominators, groups, data_type="SR", Poisson_limits=T, OD_adjust=T)
```
They can't do the same for the other data types, they can only request adjusted limits and poisson limits:
```r
funnel_plot(numerators, denominators, groups, data_type="PR", Poisson_limits=T, OD_adjust=T)
```

This PR generalises the package by replacing `Poisson_limits` and `OD_adjust` with `draw_unadjusted` and `draw_adjusted`:
```r
funnel_plot(numerators, denominators, groups, data_type="PR", draw_unadjusted=T, draw_adjusted=T)
```

Where the `draw_unadjusted` flag results in Poisson limits for SR data, and calls the OD limits function with `tau2` fixed to zero for RC and PR data (i.e., basic normal approximation).

As part of this, I slightly refactored the approach to constructing the control limits. The current approach has separate (mostly) identical functions to calculate the limits for the input denominators and the denominators for plotting. I've re-worked this as a single function to calculate the limits for both, with an inner join to extract the control limits matching the input denominators.

I've made sure to keep the returned variable naming consistent, so the only user-facing change is the argument names (`draw_unadjusted` & `draw_adjusted`)

### CODE REVIEW

**Comment by chrismainey** [comment]
Hi @andrjohns !  Thank you very much for your contribution.  It's very welcome.  I've been taking some time away from this for a while, so I'm sorry for delay.  I will be picking this up again around September/October time, and would be good to hear more about your use case and how it could be improved. Mind if I contact you in a month or two?

This is a great idea.  It was my first package release, and has changed quite a lot since the original design.  I'm keen to make it as generalisable as possible, and easier to extend with different assumptions etc.  Will review this in the next few days, update vignettes / readme page if required too.

**Comment by andrjohns** [comment]
No worries at all! I'll fixup the vignette errors that caused the test failures so it's ready for review. Definitely feel free to get in touch when you have time as well. My work will be very funnelplot-heavy for a while, so my employer is happy for me to be contributing to the package during work as well. Feel free to keep a wishlist of things you'd like implemented!

**Review by chrismainey — APPROVED** [review]
Seems very sensible to generalise the language, and put the limit calc into the function call.  All looks good here.

**Comment by chrismainey** [comment]
I'm happy to add those changes.  I think the z-score transformation process is about making it as normal as possible before back transforming. I'd be interested in you thoughts around using a normal approximation with the PR limits, or whether we could apply some form of exact binomial limit.

**Pull request merged**
